import json
import sys
import os
import time  # Import time for rate limiting
import random  # Import random for jitter

# Import the Gemini library
import google.generativeai as genai


# Define the list of skills
# This list is taken directly from your mock.js file provided earlier.
skillsList = [
  "Finance and Accounts",
  "CA",
  "Accounting",
  "Financial Analysis",
  "Financial Reporting",
  "Banking",
  "Risk Management",
  "Budgeting",
  "Financial Planning",
  "Financial Modeling",
  "Compliance",
  "Audit",
  "Forecasting",
  "Financial Control",
  "Taxation",
  "Investment Banking",
  "Financial Operations",
  "Internal Audit",
  "Reconciliation",
  "Credit Risk",
  "Chief Financial Officer",
  "BFSI Sales",
  "Valuation",
  "Credit Analysis",
  "GAAP",
  "CFA",
  "Financial Research",
  "Big4",
  "Variance Analysis",
  "Accounts Payable",
  "IFRS",
  "MIS",
  "Due Diligence",
  "Accounts Receivable",
  "Corporate Banking",
  "Treasury",
  "Corporate Finance",
  "Banking Operations",
  "Internal Control",
  "ICWA",
  "Equity Research",
  "M&A",
  "Fund Raising",
  "Direct Tax",
  "Cash Management",
  "CPA",
  "Risk Modeling",
  "Private Equity",
  "Costing",
  "Indirect Taxation",
  "Equity Analysis",
  "Statutory Audit",
  "Financial Consulting",
  "Banking Head",
  "Operational Risk",
  "SOX",
  "Market Risk",
  "Derivatives",
  "Capital Markets",
  "Quant",
  "Underwriting",
  "Investor Relations",
  "Transfer Pricing",
  "Wealth Management",
  "Credit Appraisal",
  "Regulatory Reporting",
  "Risk Analytics",
  "Project Finance",
  "Retail Banking",
  "Project Management",
  "FX",
  "Credit Rating",
  "Trading",
  "Fixed Income",
  "Credit Policy",
  "Assurance",
  "Basel",
  "Fund Management",
  "Analytics",
  "Origination",
  "Stress Testing",
  "Investment Research",
  "Statistics",
  "Portfolio Management",
  "Credit Research",
  "CS",
  "Credit Operations",
  "VaR",
  "Fund Accounting",
  "SAS",
  "Fraud Analysis",
  "Transformation",
  "Collection",
  "Venture Capital",
  "Process Excellence",
  "Goods & Services Tax",
  "Record To Report",
  "Product Control",
  "Enterprise Risk",
  "Actuarial",
  "Governance",
  "Regulatory Compliance",
  "Model Validation",
  "AML",
  "Debt Syndication",
  "KYC",
  "Commercial Banking",
  "Private Banking",
  "Trade Finance",
  "Asset Management",
  "Business Analysis",
  "Collection Operations",
  "Commercial",
  "Cost Control",
  "Wholesale Banking",
  "Credit Control",
  "Change Delivery",
  "Middle Office",
  "Six Sigma",
  "Procure To Pay",
  "Structured Finance",
  "Order To Cash",
  "Banking Sales",
  "Cost Accounting",
  "Goods & Services Tax",
  "Investment Banking Operations",
  "Corporate Strategy",
  "Insurance Operations",
  "Settlements",
  "Lean",
  "CCAR",
  "BPR",
  "Consulting - BFSI",
  "Python",
  "Liquidity Risk Management",
  "Infrastructure Finance",
  "SQL",
  "Hedge Fund",
  "Startup",
  "Real Estate Investment",
  "Pricing Analysis",
  "VAT",
  "Cost Management",
  "CAPEX",
  "Equity Valuation",
  "Loss Given Default",
  "Probability of Default",
  "IPO",
  "Algorithmic Trading",
  "Broking",
  "Macroeconomics",
  "Exposure At Default",
  "Trade Operations",
  "eCommerce",
  "Loan Operations",
  "Fixed Income Research",
  "Data Management",
  "Payroll",
  "Blackbelt",
  "Econometrics",
  "LLB",
  "Research",
  "Service Delivery",
  "HFT",
  "Quantitative Trading",
  "Billing",
  "Strategy Consulting",
  "Product Management",
  "Statistical Modeling",
  "Equity Sales",
  "Management Accounting",
  "Transition Management",
  "Fund Administration",
  "Payments",
  "Quality",
  "Legal Entity Control",
  "Sales",
  "Basel II",
  "Program Management",
  "SAP FICO",
  "Equity Trading",
  "Liquidity Reporting",
  "Collateral Management",
  "Debt Restructure",
  "Equity Derivatives",
  "Asset Liability Management",
  "Claims",
  "Economic Research",
  "Data Analytics",
  "PMP",
  "Forensic Investigation",
  "PMO",
  "Revenue Management",
  "Process Automation",
  "Forensic",
  "Sales Accounting",
  "Client Services",
  "Corporate Actions",
  "SAP Services",
  "Basel III",
  "Mortgage Operations",
  "NGO",
  "Brokerage",
  "Client Relationships",
  "Executive Assistant",
  "Independent Price Verification",
  "Pricing Strategy",
  "Business Intelligence",
  "Supply Chain Finance",
  "Commodity Trading",
  "Training and Development",
  "Securities Operations",
  "Futures & Options",
  "Reference Data",
  "COO",
  "Litigation",
  "IT Consulting",
  "Surveillance",
  "Quality Assurance",
  "Trade Support",
  "Opex",
  "Economics",
  "RFP",
  "Automation",
  "Corporate Sales",
  "Digital Transformation",
  "PhD",
  "Hyperion",
  "Revenue Assurance",
  "Process Design",
  "B2B Sales",
  "CEO",
  "BFSI Marketing",
  "Stressed Assets",
  "Reinsurance",
  "Client Onboarding",
  "Mutual Fund Operations",
  "IT Audit",
  "Microfinance",
  "Option Trading",
  "Functional Consultant",
  "Machine Learning",
  "BPO Operations",
  "Contract Management",
  "Loss Forecasting",
  "Client Management",
  "Business Continuity",
  "Custody & Fund Services",
  "Oracle",
  "Customer Service",
  "Vendor Management",
  "Economist",
  "Trade Surveillance",
  "Institutional Sales",
  "Marketing",
  "Sales Head",
  "Fraud Analytics",
  "Index Research",
  "Asset Services",
  "Tableau",
  "Business Alliances",
  "Robotics",
  "Digital Banking",
  "Solution Design",
  "Prime Brokerage",
  "Transfer Agency",
  "Data Modeling",
  "IT Project Management",
  "General Management",
  "IT Jobs in BFSI",
  "Presales",
  "BPM",
  "IT Risk Management",
  "Delivery Management",
  "Corporate Law",
  "Client Engagement",
  "SAP HANA",
  "Proprietary Trading",
  "Rural Banking",
  "IT Business Analyst",
  "Editorial",
  "Data Visualization",
  "Consulting Sales",
  "Content Writing",
  "Customer Experience",
  "Planning",
  "Information Security",
  "IT Controls",
  "Product Pricing",
  "Predictive Modeling",
  "Bid Management",
  "Procurement",
  "BPO Solutions",
  "Legal Jobs in BFSI",
  "Recruitment",
  "Regulatory Affairs",
  "Contracts",
  "Revenue Planning",
  "HR Jobs in BFSI",
  "Proposal",
  "Equity Syndication",
  "Administration",
  "Expat Management",
  "Big Data",
  "AMC",
  "Finance Transformation",
  "Data Mining",
  "Spend Analysis",
  "Content Management",
  "SAP FI",
  "Professional Ethics",
  "Campaign Management",
  "Data Science",
  "Data Quality",
  "Market Research",
  "Knowledge Management",
  "Sales Strategy",
  "BPO Presales",
  "Quality Control",
  "Sustainability",
  "Product Development",
  "Practice Management",
  "LLM",
  "Talent Acquisition",
  "PMS",
  "Channel Management",
  "Key Account Management",
  "Techno Functional",
  "ERP",
  "Legal",
  "Trade Sales",
  "Faculty",
  "Sales Planning",
  "Digital Marketing",
  "SAP CO",
  "IT Compliance",
  "Commodity Research",
  "Liasioning",
  "HR Operations",
  "Agri",
  "Learning and Development",
  "IT Product Management",
  "Data Governance",
  "Web Analytics",
  "Social Media",
  "Govt Relations",
  "Legal Head",
  "Corporate Affairs",
  "Academia",
  "BPO Quality",
  "Remittance",
  "Distribution",
  "Securitization",
  "Cofounder",
  "Option Pricing",
  "Operations Head",
  "Content Development",
  "Change Management",
  "Compensation and Benefits",
  "Global Mobility",
  "Vigilance",
  "Record To Pay",
  "Operations",
  "SEM / SEO",
  "Leasing",
  "Supply Chain",
  "CISA",
  "Practice Head",
  "Account Management",
  "Source To Pay",
  "SAP Treasury",
  "Inventory Management",
  "Trade Control",
  "HR Business Partner",
  "Solution Architect",
  "Peoplesoft",
  "Delivery Head",
  "TQM",
  "Export",
  "ESG",
  "Agile",
  "New Product Development",
  "CRM",
  "SAP COPA",
  "Marketing Head",
  "Artificial Intelligence",
  "Education Operations",
  "Online Product Management",
  "Customer Service Head",
  "Security Operations",
  "HR Head",
  "Predictive Analytics",
  "HR Generalist",
  "QMS",
  "IT Security",
  "Bancassurance",
  "Master Data Management",
  "Accounts Recievable",
  "Public Policy",
  "Brand Management",
  "Import",
  "eLearning",
  "Murex",
  "Data Scientist",
  "Innovation",
  "Sourcing",
  "Logistics",
  "Real Estate Sales",
  "Techno Commercial",
  "BPO Solution Design",
  "Sales Support",
  "Forensic Technology",
  "Excise",
  "HR Jobs in IT/ITeS",
  "Marketing Communications",
  "Mobile Banking",
  "Recruitment Sales",
  "BPO Head",
  "NLP",
  "Public Relations",
  "Benefits and Rewards",
  "Forex",
  "Order Management",
  "Email Marketing",
  "ALM",
  "Cyber Security",
  "Solutions Sales",
  "FMCG Sales",
  "Online Marketing",
  "Performance Marketing",
  "SAP MM",
  "Grant Management",
  "EPM",
  "Entrepreneur In Residence",
  "Purchase",
  "Finance Controller",
  "BPO Training",
  "Catastrophe Modeling",
  "Labour Laws",
  "BlockChain",
  "Sales Training",
  "SAP SD",
  "Islamic Banking",
  "Retail Sales",
  "Franchise Development",
  "SAP BPC",
  "Govt Sales",
  "IPR",
  "Account Receivable",
  "HR Jobs in Mfg",
  "Finacial Analysis",
  "Data Warehousing",
  "CSR",
  "Retail Analytics",
  "Migration",
  "FMCG Marketing",
  "Marketing Analytics",
  "Customer Success",
  "Healthcare Sales",
  "Tendering",
  "Content Marketing",
  "Assessment",
  "Benchmarking",
  "IT Change Management",
  "Organization Development",
  "SAP GRC",
  "Compensation and Rewards",
  "Consumer Internet",
  "SAP FSCM",
  "Market Intelligence",
  "SAP TRM",
  "Product Marketing",
  "Trading Analysis",
  "BPO Sales",
  "Education Sales",
  "Category Management",
  "Cost Reporting",
  "Consulting - Infra",
  "Commercial Accounting",
  "Capacity Planning",
  "Direct Taxation",
  "Trade Services",
  "Technical Architect",
  "Instructional Design",
  "Financial Modelling",
  "Plant Operations",
  "Mfg Operations",
  "Ikya Investment Banking",
  "Licensing",
  "Accounts Receivables",
  "Export Documentation",
  "Industrial Relations",
  "HR Compliance",
  "CTO",
  "Social Work",
  "IT Procurement",
  "Consulting - Oil and Gas",
  "International Sales",
  "Online Sales",
  "Credit Management",
]
GEMINI_API_KEY = "AIzaSyCILU-_ezGfu3iojbS-hFe9-Fil4klNOlo" # <-- REPLACE THIS PLACEHOLDER

genai.configure(api_key=GEMINI_API_KEY)

# Choose the Gemini Embedding model name.
# This MUST match the model name used in your Node.js code (analyseIdealCandidate route).
EMBEDDING_MODEL_NAME = 'models/embedding-001'  # Or 'text-embedding-004' if you prefer higher quality

# Define the output file name
OUTPUT_FILE = 'skill_embeddings_gemini.json' # Save to a different file to avoid overwriting the old one


def generate_embedding_with_retry(text, model_name, max_retries=3, initial_delay=1):
    """
    Generates an embedding for a single text string using Gemini API with retry logic
    and a small delay.
    """
    delay = initial_delay
    for i in range(max_retries):
        try:
            # Add a small delay to respect API rate limits
            time.sleep(delay)

            # Use the embed_content method for the Gemini embedding model
            response = genai.embed_content(
                model=model_name,
                content=text,
                task_type="SEMANTIC_SIMILARITY" # Recommended task type for search/similarity
            )
            # The embedding is in the 'embedding' field of the response dictionary
            return response['embedding']

        except Exception as e:
            print(f"Attempt {i+1}/{max_retries} failed for '{text}': {e}", file=sys.stderr)
            if i < max_retries - 1:
                # Exponential backoff with jitter
                delay *= 2
                jitter = random.uniform(0, delay * 0.1) # Add random jitter
                delay += jitter
                print(f"Retrying '{text}' in {delay:.2f} seconds...", file=sys.stderr)
            else:
                print(f"Max retries reached for '{text}'. Skipping.", file=sys.stderr)
                return None # Return None if all retries fail


def generate_and_save_gemini_embeddings(skills, model_name, output_file):
    """
    Generates embeddings for a list of skills using Gemini API
    and saves them to a JSON file.
    """
    print(f"Generating embeddings for {len(skills)} skills using Gemini model: {model_name}...")

    output_data = []
    for i, skill in enumerate(skills):
        # Print progress
        if (i + 1) % 10 == 0 or i == 0 or i == len(skills) - 1:
             print(f"Processing skill {i + 1}/{len(skills)}: '{skill}'")

        embedding = generate_embedding_with_retry(skill, model_name)

        if embedding:
            output_data.append({
                "skill": skill,
                "embedding": embedding # Gemini embeddings are already lists of floats
            })
        else:
            # This message is already printed by generate_embedding_with_retry
            pass

    print(f"\nSaving embeddings to {output_file}...")
    try:
        with open(output_file, 'w') as f:
            # Use indent for pretty printing - useful for checking the file
            # Remove indent=2 for smaller file size in production
            json.dump(output_data, f, indent=2)

        print(f"Embeddings successfully saved to {output_file}")
        print(f"Total skills processed successfully: {len(output_data)}")
        if output_data:
             print(f"Embedding dimension: {len(output_data[0]['embedding'])}")
        else:
             print("No embeddings were successfully generated.")

    except Exception as e:
        print(f"Error saving embeddings to file {output_file}: {e}", file=sys.stderr)


if __name__ == "__main__":
    # Make sure the skillsList above is complete
    generate_and_save_gemini_embeddings(skillsList, EMBEDDING_MODEL_NAME, OUTPUT_FILE)

# --- END OF FILE generate_skill_embeddings_gemini.py ---